const SET_MY_CHARACTER = 'SET_MY_CHARACTER';
const SET_PARTY_CHARACTERS = 'SET_PARTY_CHARACTERS';
const CHANGE_PARTY_CHARACTER = 'CHANGE_PARTY_CHARACTER';
const CHANGE_SKILL_VIEW = 'CHANGE_SKILL_VIEW';

export default {
  SET_MY_CHARACTER,
  SET_PARTY_CHARACTERS,
  CHANGE_PARTY_CHARACTER,
  CHANGE_SKILL_VIEW,
} as const;
