const GET_CHARACTERS = 'GET_CHARACTERS';
const SET_MY_CHARACTER_NAME = 'SET_MY_CHARACTER_NAME';
const SELECT_PARTY_CHARACTER_NAME = 'SELECT_PARTY_CHARACTER_NAME';
const SET_PARTY_CHARACTER_NAMES = 'SET_PARTY_CHARACTER_NAMES';
const SELECT_SKILL_TAB = 'SELECT_SKILL_TAB';

export default {
  GET_CHARACTERS,
  SET_MY_CHARACTER_NAME,
  SELECT_PARTY_CHARACTER_NAME,
  SET_PARTY_CHARACTER_NAMES,
  SELECT_SKILL_TAB,
} as const;
