const SET_DICE_COUNT = 'SET_DICE_COUNT';
const SET_DICE_SIZE = 'SET_DICE_SIZE';
const SET_JUDGEMENT_NUMBER = 'SET_JUDGEMENT_NUMBER';
const SET_ROLLING_TYPE = 'SET_ROLLING_TYPE';
const SET_GLOBAL_RESULT = 'SET_GLOBAL_RESULT';
const SET_LOCAL_RESULT = 'SET_LOCAL_RESULT';
const TOGGLE_DICE_LOG = 'TOGGLE_LOG';

export default {
  SET_DICE_COUNT,
  SET_DICE_SIZE,
  SET_JUDGEMENT_NUMBER,
  SET_ROLLING_TYPE,
  SET_GLOBAL_RESULT,
  SET_LOCAL_RESULT,
  TOGGLE_DICE_LOG,
} as const;
