const SET_CHARACTER_NAME = 'SET_CHARACTER_NAME';
const SET_CHARACTER_PARAMS = 'SET_CHARACTER_PARAMS';
const SET_CHARACTER_SKILLS = 'SET_CHARACTER_SKILLS';

export default {
  SET_CHARACTER_NAME,
  SET_CHARACTER_PARAMS,
  SET_CHARACTER_SKILLS,
} as const;
