const CHANGE_CHARACTER_NAME = 'CHANGE_CHARACTER_NAME';
const CHANGE_CHARACTER_PARAMS = 'CHANGE_CHARACTER_PARAMS';
const CHANGE_CHARACTER_SKILLS = 'CHANGE_CHARACTER_SKILLS';
const CHANGE_EDIT_CHARACTER = 'CHANGE_EDIT_CHARACTER';
const SET_CHARACTER_ALL_PARAMS = 'SET_CHARACTER_ALL_PARAMS';

export default {
  CHANGE_CHARACTER_NAME,
  CHANGE_CHARACTER_PARAMS,
  CHANGE_CHARACTER_SKILLS,
  CHANGE_EDIT_CHARACTER,
  SET_CHARACTER_ALL_PARAMS,
} as const;
