const CHANGE_CHARACTER_NAME = 'CHANGE_CHARACTER_NAME';
const CHANGE_CHARACTER_PARAMS = 'CHANGE_CHARACTER_PARAMS';
const CHANGE_CHARACTER_SKILLS = 'CHANGE_CHARACTER_SKILLS';
const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';

export default {
  CHANGE_CHARACTER_NAME,
  CHANGE_CHARACTER_PARAMS,
  CHANGE_CHARACTER_SKILLS,
  TOGGLE_EDIT_MODE,
} as const;
