const GET_CHARACTERS = 'FIREBASE/GET_CHARACTERS';
const GET_DICELOGS = 'FIREBASE/GET_DICELOGS';
const ADD_CHARACTER_START = 'FIREBASE/ADD_CHARACTER_START';
const ADD_CHARACTER_SUCCEED = 'FIREBASE/ADD_CHARACTER_SUCCEED';
const ADD_CHARACTER_FAIL = 'FIREBASE/ADD_CHARACTER_FAIL';
const ADD_DICELOG_START = 'FIREBASE/ADD_DICELOG_START';
const ADD_DICELOG_SUCCEED = 'FIREBASE/ADD_DICELOG_SUCCEED';
const ADD_DICELOG_FAIL = 'FIREBASE/ADD_DICELOG_FAIL';
const UPDATE_CHARACTER_START = 'FIREBASE/UPDATE_CHARACTER_START';
const UPDATE_CHARACTER_SUCCEED = 'FIREBASE/UPDATE_CHARACTER_SUCCEED';
const UPDATE_CHARACTER_FAIL = 'FIREBASE/UPDATE_CHARACTER_FAIL';

export default {
  GET_CHARACTERS,
  GET_DICELOGS,
  ADD_CHARACTER_START,
  ADD_CHARACTER_SUCCEED,
  ADD_CHARACTER_FAIL,
  ADD_DICELOG_START,
  ADD_DICELOG_SUCCEED,
  ADD_DICELOG_FAIL,
  UPDATE_CHARACTER_START,
  UPDATE_CHARACTER_SUCCEED,
  UPDATE_CHARACTER_FAIL,
} as const;
